### PR TITLE
Pull req/hw test improvements

### PR DESCRIPTION
**Pull request by dreimers**
This improves the hardware tests by:
- adding mag sensor test
- better naming of the nodes under test
- Typos/Whitespace/Indention fixes

Fixes for compatibility to upstream including:
- Network stack configuration (contiki-os pr  #864)
- RIME Header File path & linkaddr_t

### CODE REVIEW

**Comment by gvz** [comment]
test this please

**Comment by ejoerns** [comment]
:+1: Looks like good improvements! Just added a few minor comments you might check before this patch is applied.

**Comment by dreimers** [comment]
On https://github.com/ibr-cm/contiki-inga/pull/46#commitcomment-10907573
We reduced the number of packets to receive for successfully complete the test because the
packet lost in this environment is high so you would have to redo the test although the hardware
is fine.
This test is only good enough to tell if the radio and the connection between radio an mcu is OK.
To test and measure the quality of the HF part like the antenna we need a more extensive testing.

On https://github.com/ibr-cm/contiki-inga/pull/46#commitcomment-10907570
The sensor drivers missing the ability to satisfy the test. I added some TODOs to make this more clear. I also opened an issue #47

**Comment by gvz** [comment]
test this please

**Comment by ejoerns** [comment]
The result looks ok now but I would prefer a rebase of these as we could save a lot of confusing intermediate code states ;) If you don't like rebasing it I could do that for you.

**Comment by dreimers** [comment]
done

**Comment by ejoerns** [comment]
would you agree with the referenced version? Your rebase is quite fine but misses a few squashes and code style fixes I would prefer to make history and code even more readable.
You might also reset your branch to mine if you prefer having this PR number here merged.

**Pull request closed without merging**
